source 'https://github.com/CocoaPods/Specs.git'
source 'git@coding.jiamiantech.com:ce/jiamianSpecs.git'
source 'git@coding.jiamiantech.com:ce/LRSDevRepo/LRSRepos.git'

use_frameworks!

platform :ios, '11.0'

target 'LRSNetworking_Example' do
  pod 'LRSNetworking', :path => '../'
  pod 'ReactiveObjC'
  pod 'JSONModel', '~> 1.7.0'
  pod 'JMProgressHUD'
  pod 'LRSTDLib'
  pod 'LRSWhiteBoxQA', :git => 'git@coding.jiamiantech.com:ce/LRSWhiteBox.git'

  target 'LRSNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
end
