use_frameworks!

platform :ios, '9.0'

target 'LRSNetworking_Example' do
  pod 'LRSNetworking', :path => '../'

  target 'LRSNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
